### ISSUE TITLE
搜索功能不可用

### ISSUE THREAD

**Issue by goodryb** [PeterDing/chord#19]
macOS 10.14.4
v0.2.8

search里面输入歌名，回车搜索没反应

![image](https://user-images.githubusercontent.com/3907975/55929682-584b9c00-5c50-11e9-8dd7-103ea843de8f.png)

**Comment by PeterDing** [comment]
@goodryb 能贴一下 DevTools -> Console 中显示的错误吗

<img width="326" alt="Screen Shot 2019-04-11 at 11 59 24 AM" src="https://user-images.githubusercontent.com/670690/55929948-af9e3c00-5c51-11e9-88ab-1251be69e7d1.png">

**Comment by goodryb** [comment]
@PeterDing ru如下
![image](https://user-images.githubusercontent.com/3907975/55931039-86cc7580-5c56-11e9-89a1-ea3620f8eb1d.png)

**Comment by PeterDing** [comment]
QQ搜索的结果中有之前没发现的非正常的歌曲。
如 https://y.qq.com/n/yqq/song2/112/0045hAmL0VbG1A.html
