### ISSUE TITLE
希望增加歌词

### ISSUE THREAD

**Issue by kevinlovo** [PeterDing/chord#2]
![image](https://user-images.githubusercontent.com/25859959/49662311-6319d880-fa86-11e8-90c7-60e772687f70.png)

左下角的专辑封面可以设计成点击一下弹出一个页面放歌词和专辑大封面，像listen1这样。现在是点击向左收起，感觉没有必要。
![image](https://user-images.githubusercontent.com/25859959/49662080-e1c24600-fa85-11e8-9ff3-b0eae793afb6.png)

**Comment by flystar233** [comment]
强烈增加歌词功能~

**Comment by PeterDing** [comment]
歌词显示预计会在 v0.2.0 加入

**Comment by PeterDing** [comment]
歌词显示功能已经加入v0.2.0版本，可以到 https://github.com/PeterDing/chord/releases 下载
