### ISSUE TITLE
虾米音乐和网易云点了login  没反应，QQ的就可以登

### ISSUE THREAD

**Issue by pithecanthrope** [PeterDing/chord#21]
虾米音乐和网易云点了login  没反应，QQ的就可以弹出新窗口 可以正常登陆。
![image](https://user-images.githubusercontent.com/49546486/56013649-6b2fa080-5d24-11e9-91b7-79b0cd0084dd.png)

**Comment by PeterDing** [comment]
虾米目前只可以用账号登录，网易只能用网易的邮箱登录。

**还有，目前如果账号信息速入错误，点击登录后是不会有登录错误提示的。**
登录结果提示要在后一个版本加入。
