### ISSUE TITLE
无法使用网易云登陆

### ISSUE THREAD

**Issue by NicoOrz** [PeterDing/chord#33]
已经尝试过使用163登陆 但依然提示Login Fail。已确认帐号密码无误

**Comment by Jonnyan404** [comment]
所有关联的登录方式,我也都试了,完全不行.

**Comment by PeterDing** [comment]
问题已经解决，用 v0.2.16

**Comment by bigshans** [comment]
网易云音乐用最新版的仍然豋不上。

**Comment by PeterDing** [comment]
@bigshans 目前网易音乐 (https://music.163.com/) 只能使用**网易邮箱帐号**登录。请确定输入的帐号和密码能在 https://music.163.com/ 登录后，再在 chord 上登录。

**Comment by Sa1koro** [comment]
```
Login Fail
login error
NETEASE
```
邮箱账号在网页版上是正常登录使用的
