### ISSUE TITLE
win版本无法正常使用

### ISSUE THREAD

**Issue by DatMCHacker** [PeterDing/chord#38]
登陆网易云后打开Your Library并没有任何东西出现，

**Comment by PeterDing** [comment]
`Your Library` 是你在 chord 上保存后的音乐，比如，在歌曲，专辑，艺人，歌单上右键点击，然后选择保存。
用户登录后，勾选 `Sync To Origin` 会将之后在 chord 保存的音乐同步到对应的音乐平台，在勾选 `Sync To Origin` 前保存的音乐是不会同步到对应的音乐平台的。
`Your Library` 也不会同步登录后的账户，如果要查看登录用户的歌曲，专辑等，需要点击 `Preferences` 里的登录用户。
