### ISSUE TITLE
Windows如何打开歌词呀？？？

### ISSUE THREAD

**Issue by hulesley** [PeterDing/chord#49]
Windows如何打开歌词呀？？？

**Comment by PeterDing** [comment]
<img width="1140" alt="Screen Shot 2020-06-01 at 9 42 29 PM" src="https://user-images.githubusercontent.com/670690/83415165-41b66480-a451-11ea-916e-7b8c92ec031d.png">

**Comment by hulesley** [comment]
OKOK，太隐蔽了，是我英文不好哈哈哈哈
辛苦你为我解答了

Peter Ding <notifications@github.com> 于2020年6月1日周一 下午9:46写道：

**Comment by hulesley** [comment]
我又来了，那个参数设置在哪， 然后是设置啥东西的哈哈哈哈哈，
然后还有一个网易云的登录一直是错误，不知道是不是只有我有这个原因
不要嫌弃我😅😅😅

Peter Ding <notifications@github.com> 于2020年6月1日周一 下午11:03写道：
