### ISSUE TITLE
应用程序“chord”无法打开

### ISSUE THREAD

**Issue by srearnold** [PeterDing/chord#51]
OS:macos 11.0 beta2
![image](https://user-images.githubusercontent.com/35060790/87026098-d5780f00-c20d-11ea-8a8e-c6adfd146cec.png)

**Comment by PeterDing** [comment]
`dmg` 是在 travis 上构建的，用的是 `macOS 10.13`。目前 travis 不支持 `macOS 11` 的环境。构建的包可能运行不了。

你可以自己构建 `dmg` 包，参见 https://github.com/PeterDing/chord/blob/master/docs/build.md#for-macos

如果你在中国内地，为了能下载 electron，在第2步，要用下面的命令

```
ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/" \
npm --registry=https://registry.npm.taobao.org \
  --cache=$HOME/.npm/.cache/cnpm \
  --disturl=https://npm.taobao.org/dist \
  --userconfig=$HOME/.cnpmrc \
  --verbose \
  install
```
