### ISSUE TITLE
npm run compile 出错

### ISSUE THREAD

**Issue by Lancenas** [PeterDing/chord#53]
> gulp compile

[16:05:57] Using gulpfile ~/chord/gulpfile.js
[16:05:57] Starting 'compile'...
[16:05:57] Starting 'copyFiles'...
[16:05:57] Finished 'copyFiles' after 477 ms
[16:05:57] Starting 'compileTS'...
/Users/lixiao/chord/node_modules/@types/request-promise/errors.d.ts(1,21): error TS2792: Cannot find module '.'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
/Users/lixiao/chord/node_modules/@types/request/index.d.ts(24,27): error TS2792: Cannot find module 'form-data'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
src/chord/base/node/crypto.ts(46,31): error TS2345: Argument of type 'string' is not assignable to parameter of type 'BufferEncoding'.
src/chord/base/node/crypto.ts(66,33): error TS2345: Argument of type 'string' is not assignable to parameter of type 'BufferEncoding'.
src/chord/base/node/crypto.ts(81,31): error TS2345: Argument of type 'string' is not assignable to parameter of type 'BufferEncoding'.
src/chord/base/node/crypto.ts(92,31): error TS2345: Argument of type 'string' is not assignable to parameter of type 'BufferEncoding'.
src/chord/music/core/api.ts(420,83): error TS2554: Expected 1-2 arguments, but got 3.
src/chord/music/kuwo/crypto.ts(29,45): error TS2554: Expected 1-3 arguments, but got 0.
src/chord/music/kuwo/crypto.ts(290,7): error TS6133: 'decrypt' is declared but its value is never read.
src/chord/music/kuwo/parser.ts(115,18): error TS6133: 'e' is declared but its value is never read.
src/chord/music/migu/api.ts(99,13): error TS6133: 'account' is declared but its value is never read.
src/chord/music/migu/parser.ts(21,5): error TS6133: 'getUserUrl' is declared but its value is never read.
src/chord/music/netease/api.ts(433,107): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.
src/chord/music/xiami/api.ts(56,7): error TS6133: 'CNA' is declared but its value is never read.
src/chord/music/xiami/api.ts(167,13): error TS6133: 'refreshToken' is declared but its value is never read.
src/chord/music/xiami/webApi.ts(116,13): error TS6133: 'account' is declared but its value is never read.
src/chord/music/xiami/webApi.ts(121,13): error TS6133: 'userId' is declared but its value is never read.
src/chord/sound/himalaya/api.ts(182,16): error TS2304: Cannot find name 'makeRadios'.
src/chord/sound/himalaya/api.ts(193,21): error TS2304: Cannot find name 'makeRadio'.
src/chord/sound/himalaya/api.ts(366,16): error TS2304: Cannot find name 'makeRadios'.
src/chord/sound/himalaya/api.ts(394,16): error TS2304: Cannot find name 'makeRadios'.
src/chord/sound/himalaya/api.ts(403,16): error TS2304: Cannot find name 'makePodcastListOptions'.
src/chord/sound/himalaya/api.ts(438,23): error TS2304: Cannot find name 'makePodcastOptionSubs'.
src/chord/workbench/parts/common/component/radioItem.tsx(26,1): error TS6133: 'PlayIcon' is declared but its value is never read.
src/chord/workbench/parts/mainView/browser/component/home/component/albums/albumList.tsx(92,63): error TS2556: Expected 9 arguments, but got 0 or more.
src/chord/workbench/parts/mainView/browser/component/home/component/albums/albumListOptions.tsx(209,71): error TS2556: Expected 7-8 arguments, but got 0 or more.
src/chord/workbench/parts/mainView/browser/component/home/component/artists/artistListOptions.tsx(244,23): error TS2345: Argument of type '{ [x: number]: string; }' is not assignable to parameter of type 'IArtistOptionsViewState | ((prevState: Readonly<IArtistOptionsViewState>, props: Readonly<IArtistOptionsViewProps>) => IArtistOptionsViewState | Pick<...>) | Pick<...>'.
  Type '{ [x: number]: string; }' is missing the following properties from type 'Pick<IArtistOptionsViewState, "area" | "artists" | "gender" | "index" | "genre">': area, artists, gender, index, genre
src/chord/workbench/parts/mainView/browser/component/preference/configuration/configuration.tsx(49,23): error TS2345: Argument of type '{ [x: string]: any; }' is not assignable to parameter of type 'IConfigurationViewState | ((prevState: Readonly<IConfigurationViewState>, props: Readonly<any>) => IConfigurationViewState | Pick<...>) | Pick<...>'.
  Type '{ [x: string]: any; }' is missing the following properties from type 'Pick<IConfigurationViewState, "view" | "proxy">': view, proxy
src/chord/workbench/parts/player/browser/action/playAlbum.ts(3,1): error TS6133: 'ORIGIN' is declared but its value is never read.
src/chord/workbench/parts/player/browser/action/playAlbum.ts(10,10): error TS6133: 'hasPlayItemAudio' is declared but its value is never read.
src/chord/workbench/parts/player/browser/action/playArtist.ts(3,1): error TS6133: 'ORIGIN' is declared but its value is never read.
src/chord/workbench/parts/player/browser/action/playArtist.ts(12,10): error TS6133: 'hasPlayItemAudio' is declared but its value is never read.
src/chord/workbench/parts/player/browser/action/playCollection.ts(3,1): error TS6133: 'ORIGIN' is declared but its value is never read.
src/chord/workbench/parts/player/browser/action/playCollection.ts(12,10): error TS6133: 'hasPlayItemAudio' is declared but its value is never read.
src/chord/workbench/parts/player/browser/action/playUser.ts(3,1): error TS6133: 'ORIGIN' is declared but its value is never read.
src/chord/workbench/parts/player/browser/action/playUser.ts(12,10): error TS6133: 'hasPlayItemAudio' is declared but its value is never read.
TypeScript: 36 semantic errors
TypeScript: emit succeeded (with errors)
[16:06:15] Finished 'compileTS' after 18 s
[16:06:15] Finished 'compile' after 19 s

**Comment by PeterDing** [comment]
这些是 ts 语义错误，不影响代码逻辑。大部份是一些无用变量声明和参数不匹配问题。

`npm run compile` 完成后，运行 `npm run start` 开启程序。

**Comment by Lancenas** [comment]
> 这些是 ts 语义错误，不影响代码逻辑。大部份是一些无用变量声明和参数不匹配问题。
> 
> `npm run compile` 完成后，运行 `npm run start` 开启程序。

是不影响打包使用，谢谢！
