### ISSUE TITLE
chord变速是否用的Howler.js，为什么我用Howler变速后，调也变了？而你的却不变

### ISSUE THREAD

**Issue by tanker5258** [PeterDing/chord#56]
Ding兄，您好。

       这几天在研究您的chord，因为我是初学，也只是大概看懂vue的代码。recat的代码看起来有点吃力，用调试工具，看了半天，也没有找到  变速0.5-4.0那个工具栏的click点击事件代码在哪里，看见您引用了howler.js。请问这个变速功能您是否用的是 howler.js。为什么我用howler.js变速后，音调变得很难听，同一首歌，跟你的变速音调不一样。
       还肯请您百忙中给予解答。谢谢啦。我的QQ  19771800  

       致，工作顺利！

      英奇剑   2021.1.11

**Comment by PeterDing** [comment]
@tanker5258 变速调用的的确是 `Howler.js` 的 api。

下面是相关的代码：

https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/parts/player/browser/action/changeRate.ts#L5
https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/api/node/audio.ts#L148
https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/api/node/audio.ts#L88

view 代码：
https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/parts/player/browser/component/rate.tsx#L8

**Comment by tanker5258** [comment]
非常感谢Ding兄，我慢慢研究。如果有不懂的地方，可能还要给您添麻烦。：）&nbsp;


小快笔感谢您的支持!有任何问题欢迎随时联系！

小快笔软件官方网站： www.xkbsoft.com&nbsp;&nbsp;&nbsp;&nbsp; 英奇剑(QQ:19771800) 
 




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peter Ding"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 中午12:09
收件人: "PeterDing/chord"<chord@noreply.github.com&gt;; 
抄送: "小快笔软件"<19771800@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PeterDing/chord] chord变速是否用的Howler.js，为什么我用Howler变速后，调也变了？而你的却不变 (#56)





 
@tanker5258 变速调用的的确是 Howler.js 的 api。
 
下面是相关的代码：
 
https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/parts/player/browser/action/changeRate.ts#L5
 https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/api/node/audio.ts#L148
 https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/api/node/audio.ts#L88
 
view 代码：
 https://github.com/PeterDing/chord/blob/f8062920604e70a97e40ed13fa1679d458329ca2/src/chord/workbench/parts/player/browser/component/rate.tsx#L8
