### ISSUE TITLE
使用搜索后会黑屏

### ISSUE THREAD

**Issue by GTrunSec** [PeterDing/chord#58]
这个问题，我不清楚是怎么回事。我第一次使用是ok的。然后清除了用户数据 `~/.config/chord` 和`~/.chord`

突然再次启动搜索就出现了这个问题。时好时坏

![image](https://user-images.githubusercontent.com/21156405/109459987-bafcdb00-7a14-11eb-8515-b1146d63f693.png)

System:NixOS, Appimage

**Comment by PeterDing** [comment]
chord 没有缓存，只有配置文件和用户数据，这些都存放在 `~/.chord`。

-------

从图中报错来看，应该是对 Himalaya 搜索时，数据解析出错了。能提供一下搜索的关键字吗，方便复现错误。

**Comment by GTrunSec** [comment]
结构展示，
```
 ~/.chord/
chord-search-history.json  default-library.db         user.config
```
tree -L 1 ~/.config/chord/
/home/gtrun/.config/chord/
├── blob_storage
├── Cache
├── Code Cache
├── Cookies
├── Cookies-journal
├── Crash Reports
├── Dictionaries
├── GPUCache
├── Local Storage
├── Network Persistent State
└── Preferences

``
我就随便搜索的，这个问题时好时坏。同样的关键字如`开心`

**Comment by GTrunSec** [comment]
从debug 窗口是 Himalaya API 搜索时，数据解析出错了。但我前面搜索是ok的，第二次启动同样的关键字就会出错黑屏。

**Comment by PeterDing** [comment]
<img width="1262" alt="Screen Shot 2021-03-01 at 3 02 19 PM" src="https://user-images.githubusercontent.com/670690/109463310-bb8e8380-7a9f-11eb-89d8-8d510189d3e9.png">

我使用了初始配置，chord 版本 v0.2.37，系统 macos，关闭了代理。但是无法复现这个错误。

黑屏是因为数据出错，react 无法完成渲染导致的。你那每次出现黑屏都是应为你截图中的错误吗？

**Comment by GTrunSec** [comment]
是的都是我截图中的错误，这个是时好时坏（几率很高）。我不是macos，我是 linux NixOS. appimage打包下运行的。比如刚才是坏的，现在同样的关键字就突然好了

**Comment by PeterDing** [comment]
你用的版本也是 v0.2.37 ？

**Comment by GTrunSec** [comment]
> 你用的版本也是 v0.2.37 ？

你试试关键字`别告诉她`。版本是没问题的0.2.37
![image](https://user-images.githubusercontent.com/21156405/109464655-d9b2a000-7a1b-11eb-8d6b-a2f2ee3a98e8.png)

**Comment by GTrunSec** [comment]
我目前的环境是在国外，程序运行是nix下打包运行的chord appimage. 在debian nix上也复现了这个错误

**Comment by PeterDing** [comment]
我应该明白是怎么回事了。我很久没用 himalaya 了，也因为我在墙内且没设代理，所有 himalaya 的请求都报错了，结果chord的api都返回了空数据，所以我这没有异常。而你那 himalaya 返回了数据，可能数据格式变了，导致数据处理出错，所以黑屏了。

**Comment by GTrunSec** [comment]
好的麻烦你修复一下，要么给用户关闭搜索API的选项在UI或者user config都行disable search-source.都行

**Comment by PeterDing** [comment]
v0.2.38 修复了这个bug。试试看，是否可行。

**Comment by GTrunSec** [comment]
可以了，完美运行。感谢！
