### ISSUE TITLE
Proxy声明错字

### ISSUE THREAD

**Issue by zcx1218029121** [PeterDing/chord#64]
为了正常使用使用 Himalaya，用户需要在系统 hosts 文件中添加下面一条:
47.254.50.181 api.himalaya.com

Windows 用户设置 hosts 文件 见： https://www.cnblogs.com/chenfei0801/p/3422985.html
MacOS，Linux 用户编辑 /etc/hosts

中国国内的用户如果要收听部分的 Himalaya 的内容，需要设置一个(科学上网)代理。
chord 默认不使用代理来访问所以的音频链接，如果音频请求出错且音频链接的域名 不属于中国，那么 chord 尝试用代理来链接。
如果用户没有设置 hosts 和 代理，可能无法搜索到 Himalaya 的内容。

错别字 ...使用代理来访问所以的音频链接.... 应该是..使用代理来访问所有的音频链接....

**Comment by PeterDing** [comment]
哈哈，多谢反馈 😄
